### ISSUE TITLE
Portals between servers in bungee network

### ISSUE THREAD

**Issue by PurpleTape** [sekwah41/Advanced-Portals#106]
Hello. The issue is that when I make portals which connect servers in bungee network together it's workd fine. But when u try use portal u will be join in destination server at position where u was logout last time. I just mean that u will be infinity:

1. Go to portal
2. tp to destination server
3. Login at destination server in portal
4. tp back to first server
5. go to step 1
...

For example we have this command:
/portal create name:NAME bungee:SERVER destination:LOC
So I think resolve that can be is tp to LOC first and then tp to SERVER

Thank you

**Comment by sekwah41** [comment]
You cannot to go destinations on other servers atm

**Comment by PurpleTape** [comment]
I know that. But i mean when use portal go to LOC first and then go to SERVER. So by this way we will logout at current server at location LOC, not at location inside portal

**Comment by sekwah41** [comment]
Due to the way that portals work I disabled it when you were using a destination and bungee else if it failed to move you you would just go to the other location or stay in the other location while its waiting to move you. I can change that back but i was gonna set your logout location with a new tag

**Comment by PurpleTape** [comment]
Ок
