### ISSUE TITLE
Destinations for Bungee

### ISSUE THREAD

**Issue by Elxafil** [sekwah41/Advanced-Portals#139]
So I've just setup this plugin though the problem is instead of sending them to the server's spawn when they change server using a portal it puts them inside the other portal on the new server and then the player just gets teleported back and forth as the portals are END_PORTAL so therefore it's horizontal and the player can not be pushed out. Is it possible to send them to a specific destination on the new server or just allow the spawn to be used the same as when they do /server <name>

**Comment by dalbodeule** [comment]
I added for #174 . this good for you.

**Comment by sekwah41** [comment]
@dalbodeule perfect, just tested and it works great. I will add auto complete and some more cross server communication in the future. I haven't messed with bungee enough tbh and was worried that the messages wouldn't carry across alongside the  transfer request due to no users being on the server beforehand.

**Comment by sekwah41** [comment]
Thanks to the pull request that had now been merged, this is now possible. I will be releasing a new version later.
