### ISSUE TITLE
Custom perm message.

### ISSUE THREAD

**Issue by AverageUnknown** [sekwah41/Advanced-Portals#144]
The default message is "[AdvancedPortals] You do not have permission to use this portal!"

Is it possible to set it to something else custom?

**Comment by sekwah41** [comment]
Not atm, you talking per portal or just generally changing the message overall?

**Comment by JySzE** [comment]
Just generally changing the message overall.

As of now im using the method of just editing the prefix from [AdvancedPortal] to my custom message. 

Which isnt that bad.. 

But if possible a way to edit this message would be amazing, im using twitchsync on my bungee servers hub and i want the people not ranked as a subscriber to be known they cant access that sub portal because they lack the subscriber rank.

**Comment by sekwah41** [comment]
Will look to add as a new tag. At the moment due to the max length of commands this can start to get a bit long. Redefining tags is already possible on the recode though if anything is too long you will be able to manually add the data.

Recently I added the delay tag so this should be similar. Its just the code gets messier and messier due to the old layout.

**Comment by TreemanKing** [comment]
@sekwah41 can be closed.
