### ISSUE TITLE
Gui closes when teleported to destination

### ISSUE THREAD

**Issue by Culup** [sekwah41/Advanced-Portals#151]
I coded a plugin with a custom gui. To open up the gui you do the command /Barbchoose. So I attached that to the portal. It opens up the gui but it closes right away after you tp to the destination specified. Is there a way to remove the destination so it doesnt tp you anywhere. Or maybe it keeps the gui open after the teleport?

**Comment by sekwah41** [comment]
What good timing I literally just opened up github and this was here. If you are using portal blocks gui's are always closed because that in vanilla cancels any gui's. You can add a command and it shouldn't say that there isn't a destination but it does move you back (so ive made it think you have warped if there is at least one command, thatll be in the next update)

**Comment by Culup** [comment]
I have set the trigger block to air, what it does is that it says you have no destination and teleports me back
I don't want it to teleport me anywhere if it is possible I would just like for me to stay in the portal and it opens the gui once or something

**Comment by Culup** [comment]
It also teleports me out of the portal area so I mostly cannot even walk in but when I am able to it closes the gui right away

**Comment by sekwah41** [comment]
Which version are you using? by my understanding what you want is the current behaviour of the latest versions.

**Comment by sekwah41** [comment]
This shouldnt happen anymore due to changes. There may be one specific case though it should be fine.
