### ISSUE TITLE
Add notblock sound for teleport

### ISSUE THREAD

**Issue by sekwah41** [sekwah41/Advanced-Portals#159]
Add noteblock ping for the teleport sounds

From https://www.spigotmc.org/threads/advanced-portals.102026/page-28#post-3432046

**Comment by axemwa** [comment]
Instead of just noteblock pling can u make it so any of [these sounds](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html) - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html are usable? That's what I meant originally not just the one sound

**Comment by axemwa** [comment]
So in the field instead of a 1 or 0 you type in a minecraft sound instead would be much easier to configure and setup then

**Comment by axemwa** [comment]
I'd suggest adding this feature for older versions of minecraft too and u could put them all into a zip folder like a lot of devs seem to be doing these days, this would also allow any other new features ot also be added in future for older miencraft versions as well

Zip example:

![image](https://user-images.githubusercontent.com/37608633/59622104-d73ce380-916f-11e9-97bf-3f23ba09903a.png)

Sound config option example:

# WarpSound generally suggested to keep the same as warpeffect but can usually be used for just the sound and no particle effects
# Enter the minecraft sound below
# Minecraft sounds for 1.13+ can be found here - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# Minecraft Sounds for 1.9 > 1.12.2 can be found here - https://helpch.at/docs/1.12.2/org/bukkit/Sound.html
# Minecraft sounds for 1.7 > 1.8 - http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html 
# 1.13 Example "WarpSound: BLOCK_NOTE_BLOCK_PLING"
WarpSound: ENTITY_ENDERMAN_TELEPORT

**Comment by sekwah41** [comment]
I'll take a look at the block one. I may be able to make some form of wrapper to sort that out. Main issue is the compatability though I could code it to just full on disable if the compatability isn't supported.

Though first I'll do the sounds and make a seperate issue for back compatability.

**Comment by sekwah41** [comment]
The reason I didn't use enum names to begin with was I was very new to plugin making 6 years ago when this started I just haven't touched it since other than porting :P

**Comment by axemwa** [comment]
Ah ok makes sense and yeah what ever is easier for you, backwards compatibility in one plugin does definitely sound better and I would have suggested that if I knew that was the easier option for sure.
I know what you mean I'm new to plugins myself and have only made 1 with no prior programming experience but it still has bugs so I'll have to re-teach myself how to do it all again as it's been a while since I've worked on it and would like to continue making new plugins in the future, it's just a lot to take in for me, the plugin I made is called NoStrip btw. 

Anyway thanx for getting back to me don't worry too much about those feature requests/suggestions if it's too difficult as they were merely suggestions for convenience and the plugin is already really good as it is you've done an excellent job with it.
