### ISSUE TITLE
Fell through the overworld and died

### ISSUE THREAD

**Issue by mark-d-holmberg** [sekwah41/Advanced-Portals#181]
I teleported from a portal several thousand blocks away from the target destination and ended up falling out of the world, died, and lost all my items. Are there safeguards in place which can prevent this? Note, the destination was inside the 12x12 grid of "spawn chunks", so the destination world should have been loaded. Has anyone else experienced this?

**Comment by sekwah41** [comment]
As teleporting is a basic call in the spigot api as well as that chunk should have been loaded this is not an issue with advanced portals. Not sure whats happened there because usually if the world doesnt load for the client the server usually rejects the movement because its impossible. It sounds like either you've hit a weird edge case or may be using a version of minecraft which doesn't perform these checks server side.

Are you using a jar such as glowstone or paperspigot?

**Comment by mark-d-holmberg** [comment]
We're on a bungee server running paper

**Comment by sekwah41** [comment]
Can you replicate this issue?

**Comment by mark-d-holmberg** [comment]
I feel like it might have to do with having a destination placed on top of a half slab. And yes, we've had this problem multiple times. I don't have the best ping to the server, and sometimes I fall through the world and it whips me back up to the target destination. Other times, I fall out of the world and die. We haven't be able to figure out an exact cause yet either. We had one player teleport from places far away, and they ended up suffocating in a wall.

**Comment by sekwah41** [comment]
Could you possibly try spigot rather than paperspigot? Usually when there are bugs with the client having not loaded the chunk the server will verify the movement and stop them falling through invisible blocks even if you are teleported inside a block the blocks surrounding it should be verified.

Or do you have void below a floating spawn?

**Comment by mark-d-holmberg** [comment]
We changed up our server architecture a bit and move to a different cloud provider. Hasn't happened since.

**Comment by sekwah41** [comment]
Ah allright, give me a shout if it happens again. If it doesn't happen for about a week I will likely pin the issue down to paperspigot or something in your setup.
