### ISSUE TITLE
Nether portal issue

### ISSUE THREAD

**Issue by NineDivinez** [sekwah41/Advanced-Portals#208]
I updated my server recently to 1.16 with bungee, advanced portals, and a couple of misc tools.  Got my portals working again to the separate servers, but when I tried going to the nether, it never sent me there.   To test it, I removed the advanced portals plugin and now I'm able to go back to the nether.  I'm not sure if I set something up incorrectly or what happened, but I would really need some help resolving this issue.

**Comment by sekwah41** [comment]
If the portal is anywhere near a portal region it won't work and that's only if the nearby portals are NETHER_PORTAL triggers. You can alter the protection region. There is also the possibility that leaving breaks the metadata so ill add a cleanup on the join event to try to fix that up.

**Comment by NineDivinez** [comment]
If the portals that I made for the server network are near a portal region..?  After I disabled the advanced portals, I noticed when you leave the nether, it takes you to the portals at spawn that I made.  So that's probably the issue then?

**Comment by sekwah41** [comment]
If you have a public server I can come and check it out when I am free though due to the current behaviour you've explained to me you have a nether portal you are trying to use normally too close to an advanced portals portal. Make them further apart.

Feel free to just send a screenshot from a distance of the nether portal and also try deleting portals.yml if you are still having the issue. Though unless I see some evidence that what I've stated above isn't the case I'm going to have to close this issue. I'll leave it open for now but also feel free to ask for help on the discord when I am online I can give you a hand as long as I am not at work.

**Comment by sekwah41** [comment]
Looks like the same issue as #228 which may be fixed now
