### ISSUE TITLE
After portal remove, region protection stays in effect.

### ISSUE THREAD

**Issue by pr0dus** [sekwah41/Advanced-Portals#235]
As mentioned in the title, after i remove a portal the region is still protected. You do not have permission to place a block here,
Permissions for default player is just to use the portal.
The error i get is listed in:

src/main/java/com/sekwah/advancedportals/bukkit/listeners/PortalProtect.java

**Comment by sekwah41** [comment]
Could you provide the full error stack trace please? It helps us track the issue back to the source :)

**Comment by pr0dus** [comment]
I am sorry but dont have a clue how.

**Comment by sekwah41** [comment]
It's just the text surrounding where you got that line from. Just that line on it's own sadly doesn't help much.

**Comment by pr0dus** [comment]
In the console it doesent show anything. In game when i deop myself i cannot put a button in the portal area or blocks where there was a portal. Because i deleted it as a op.

**Comment by sekwah41** [comment]
Given the behaviour of the code you have, there is likely another portal still in that area you are forgetting about. to avoid this we used to warn the user when portals were overlapping but due to popular demand we swapped this behavior back.

You may want to use `/portal select` and try punching the surrounding blocks to see if you select a portal you didn't think was there.

Or you could try doing `/portal show (portal name)` for all the currently active portals to see if any of them are around.

Portals will also protect in a 5 block radius around themselves by default.
