### ISSUE TITLE
Help Getting AP working again on 2 year old server.

### ISSUE THREAD

**Issue by Tyree** [sekwah41/Advanced-Portals#346]
I just resurrected an old server and AP isn't working.  I was getting a warning saying [AdvancedPortals] Material may be from old name format, but I changed the naming of STATIONARY_WATER and AIR to water and air and the warning went away, but the portals still don't work.

Only other AP related warning in the server log is:  [AdvancedPortals] Proxy features disabled for Advanced Portals as bungee isn't enabled on the server (spigot.yml) or if you are using Paper settings.velocity-support.enabled may not be enabled (paper.yml)

Any help is appreciated!

Thanks!

**Comment by sekwah41** [comment]
As we are supporting across many versions, I currently have the plugin using an older version of the materials API. I do need to update it but because it still works (first time it gets called it freezes for a second I believe). Ill have to take a look a the individual setup you have. Which version of mc are you using and which version of the plugin?

Also, the proxy support part is to make sure people using velocity or bungee enable the correct forwarding to stop players being able to send packets that trigger the proxy features. You can ignore it unless you are trying to set up desti specific bungee portals.

**Comment by sekwah41** [comment]
Feel free to send me a message here or on discord if you need any assistance.

**Comment by Tyree** [comment]
Thanks so much.
I am using spigot 1.19.3 and AP 0.9.2
Do you have a discord server or should I message you directly? Same username?

**Comment by sekwah41** [comment]
My discord server is https://discord.sekwah.com/

I am Sekwah#0001 on discord.

I will be out today but should be on later.

**Comment by sekwah41** [comment]
Actually change of plans. I'll need to be on tomorrow instead.

**Comment by Tyree** [comment]
No worries. Busy day for me too. 😊
