### ISSUE TITLE
Triggerblock only works on solid blocks when you are inside the block.

### ISSUE THREAD

**Issue by Markersx** [sekwah41/Advanced-Portals#45]
I've tried setting trigger block to solid blocks that you cannot go through and it doesn't teleport you but if I teleport inside the block then it works. For example I make a 10x10x10 portal and set the trigger block to dirt then when i stand on the dirt it doesn't teleport but if I teleport my self inside the dirt block the portal works.

**Comment by sekwah41** [comment]
The trigger block is ment to be for blocks you walk into such as air. The only "solid" blocks you can actually use are iron bars, glass panes and stairs (if layed out correctly). You have to actually be in the block to trigger it. This was added to reduce lag as it does a simple material check and very quickly can determine which portals you may be in. I could look at adding on contact however that would decrease the performance by a fair bit in comparison as you would be checking all colliding.

I can check to see if there is a block collision event but I cant see myself adding this directly into the plugin due to wanting to keep it a light weight plugin.

**Comment by sekwah41** [comment]
Due to the nature of the location checking of this plugin I will not be adding this. I should have probably said it far earlier on.
