### ISSUE TITLE
Double-teleportation using portals

### ISSUE THREAD

**Issue by Brickery** [sekwah41/Advanced-Portals#50]
To whom it may concern,

I'm trying to use a BungeeCord server with your portals plugin to move players from one Bungee server to the next. However, while moving between my lobby server and my other server (I'll just call it 'A'), I get teleported into the portal on the other server (so for example, from my lobby to A works fine, but then when I get back to my lobby, I get teleported into the portal over at my lobby and I go to the portal over at A's side, then go to the lobby, and it repeats. The timeout helps, but it's a great annoyance. I have set up both the destination tags and the bungee server tags.

Is there a way to solve this? I'm running a login plugin on the lobby server (UltraAuth) with FastLogin, other plugins are (on the lobby server and server A): 
EssentialsX (and all the other EssentialsX jars)
PEx
WorldEdit
WorldGuard
and there are some more but they aren't significant mods.

Would really appreciate if you could help! Thanks!

**Comment by sekwah41** [comment]
At the moment it is a bug with being transported to another server. Because the server automatically rejoins you where you left you are actually in a portal. So I need to fix this by seeing if I can change the server leave location. Ill update here when i find a fix but for now if its not too important add a plugin which teleport's you to the spawn when you join and that should fix it.

**Comment by LazoYoung** [comment]
You could try configuring Essentials plugin to solve this for the moment.
spawn-on-join to true will make players moved to spawn if they join the server (where the portal exists)

**Comment by sekwah41** [comment]
There is now a cooldown when joining a server as well as using a portal. There will be a better fix but this issue should be resolved for now.
